# Generated by Django 3.0.4 on 2020-07-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMaskDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maskNumber', models.FloatField(null=True)),
                ('algorithm', models.CharField(default=None, max_length=100, null=True)),
                ('com_x', models.FloatField(null=True)),
                ('com_y', models.FloatField(null=True)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='IsroBackend.ImageFileName')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePreds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('top_temp', models.FloatField(null=True)),
                ('top_height', models.FloatField(null=True)),
                ('cloud_type', models.TextField(default=None, max_length=100, null=True)),
                ('maskNumber', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='IsroBackend.ImageMaskDetails')),
            ],
        ),
    ]
