# Generated by Django 3.0.4 on 2020-07-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IsroBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMaskPreds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maskNumber', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('top_temp', models.FloatField(null=True)),
                ('top_height', models.FloatField(null=True)),
                ('cloud_type', models.TextField(default=None, max_length=100, null=True)),
                ('maskKey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='IsroBackend.ImageMaskDetails')),
            ],
        ),
        migrations.DeleteModel(
            name='ImagePreds',
        ),
    ]
