# Generated by Django 3.0.4 on 2020-08-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IsroBackend', '0004_auto_20200718_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePredicted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictionOf', models.FloatField(null=True)),
                ('pathToGif', models.CharField(default=None, max_length=100, null=True)),
                ('mse', models.FloatField(null=True)),
                ('ssim', models.FloatField(null=True)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='IsroBackend.ImageFileName')),
            ],
        ),
    ]
