# Generated by Django 3.0.4 on 2020-08-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IsroBackend', '0005_imagepredicted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagePredicted',
            new_name='ImagePredictedCNN',
        ),
    ]
