# Generated by Django 3.0.4 on 2020-08-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IsroBackend', '0007_imagepredictedmpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemaskdetails',
            name='cloudType',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
